#184: Allow custom unmarshal implementation
amzn/ion-go pull request #185
Opened 2022-01-31 23:42 UTC by errorhandler

Issue #, if available: #184

Description of changes:
Adds the unmarshalling equivalent of `Marshaler`. Allowing types to implement their own unmarshalling logic. It's basically the same implementation, but requires the `UnmarshalIon` method to be implemented with a pointer receiver as it needs to mutate the struct.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-07 23:08 UTC, popematt commented
Hi, thanks for your contribution!

It looks like the CI build failed because one of our Github Workflows was broken. I've fixed the workflow now. Do you mind rebasing your commit against the tip of `master` in `amzn/ion-go` so that we can re-run with the fixed workflow? Alternately, you could grant me permission to edit the PR, and I'll update it.

2022-02-07 23:36 UTC, popematt requested changes
Aside from one very small typo, this looks good. Thank you!

2022-02-07 23:36 UTC, popematt commented on ion/unmarshal.go
> +// Unmarshaler is the interface implemented by types that can unmarshal themselves to Ion.
```suggestion
// Unmarshaler is the interface implemented by types that can unmarshal themselves from Ion.
```

2022-02-07 23:49 UTC, popematt approved these changes

2022-02-08 17:47 UTC, merged

2023-01-04 10:04 UTC, Vingtoft commented
HI, can you please provide an example of how to use UnmarshalIon?

Given the struct:

```
type Account struct {
	Name         string          `ion:"name"`
}
```

I write the function:

```
func (a *Account) UnmarshalION(b []byte) error {
    fmt.Println("In Unmarshall")
    a.Name = "boo"
    return nil
}
```

The above implementation does not work.

Needless to say: Im learning Go. 

Thanks!